client/package-lock.json
package-lock.json
server/models/Crayon.js
server/models/Response.js
server/models/Village.js
server/models/Villager.js
server/models/index.js
server/package-lock.json

-schemas created for the village and villager models

created Village and Villager models

---

server/models/Crayon.js
server/models/Response.js
server/models/Villager.js
server/schemas/index.js
server/schemas/typeDefs.js

Created TypeDefs with schemas, queries, and mutations (still need to be tested)
Updated Crayon and Response to be schema only and imported crayon schema to be in villager schema as a subdocument

TypeDef and Schema/Models Updated

---

client/package-lock.json
server/config/connection.js
server/schemas/typeDefs.js
server/server.js

Connection to database using mongdoDB is set within connection.js
Server.js should be ready to run with Apollo Server and GraphQL
Added comments to new code.

Server.js and Connection.js

---

server/schemas/resolvers.js
server/schemas/typeDefs.js

Added resolver queries for village, villages, villager, and villagers

Added resolver queries

---

server/models/Villager.js
server/schemas/resolvers.js
server/schemas/typeDefs.js

Fixed resolver queries to show all relevant info for villages and villagers (both single and plural). Got query for request but is not showing all relevant info in graphQL

Fixed resolver queries

---

client/package-lock.json
client/package.json
client/src/App.js
client/src/components/AllRequests.js/index.js
client/src/components/CreateRequest/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/components/EditProfilePage/index.js
client/src/pages/EditProfile.js
client/src/pages/Village.js

Added the edit profile page, the form components for the page as well

Val branch

---

client/src/App.js
client/src/index.css
client/src/index.js
client/src/pages/Home.js
client/src/theme.js

Our custom color palette is now applied and available for all buttons and components
`:root {
--primary: #00425A;
--secondary: #FC7300;
--terciary: #1F8A70;
--highlight: #BFDB38;
}`

applying custom color palette using theme.js

---

server/config/seeds.js
server/models/Comment.js
server/models/Request.js
server/models/Village.js
server/models/Villager.js
server/schemas/resolvers.js
server/schemas/typeDefs.js

Fixed schemas so Villagers now have a village array and Villages now have a requests array and removed villageId from request schema. Fixed in typeDefs and resolvers and added joinVillage mutation

Fixed schemas and resolvers

---

client/src/App.js
client/src/components/AllRequests/index.js
client/src/components/CreateVillageBtn/index.js
client/src/components/Nav/index.js
client/src/pages/Village.js
client/src/utils/queries.js
server/schemas/resolvers.js

Got the Village.js to now render with the specific village information from the logged in Villager.
Removed the ID from the URL for the Village page.
Updated AllRequest page to be only request from the single village (changed it to take props from Village.js)
Query VillageID from the logged in Villager to render the appropriate information within Village page.

Fixed Village.js

---

client/src/components/ReqsByVillager/index.js
client/src/pages/Profile.js
client/src/utils/queries.js

Changed query for single villager on frontend to include more requests data (title, body, cranyons, authorId with username) and replaced query-villager-crayon with query-villager. Replaced the for loop for reqbyvillager to only get the props from the profile page for request and map through those given in prop.

Fixed Profile Request List

---

client/src/components/AllRequests/index.js
client/src/components/DeleteHook/index.js
client/src/components/EditProfilePage/index.js
client/src/components/LoginForm/index.js
client/src/components/LogoutBtn/index.js
client/src/components/ReqsByVillager/index.js
client/src/components/Signup/index.js
client/src/components/UserProfile/index.js
client/src/components/VillageInfo/index.js
client/src/pages/CreateReq.js
client/src/pages/EditProfile.js
client/src/pages/Profile.js
client/src/pages/Village.js
server/models/Villager.js

Added Auth.logout to DeleteHook so that users is kicked to home screen when profile is deleted. Also commented out unused console logs

Delete Hook update- added logout after user profile is deleted

---

client/src/components/CreateRequest/index.js
server/schemas/resolvers.js

Delete Villager request can now:
- Delete villager from front-end and logs them out (expires token)
- Delete all their request
- Delete all their request from the village request array.
- Everything works both front-end and backend.

Delete Villager Request

---

client/src/App.js
client/src/components/AllRequests/index.js
client/src/components/CommentForm/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/pages/Request.js
client/src/pages/styles/village.css
client/src/utils/queries.js
server/schemas/resolvers.js

- Single Request now displays on Request page
- Pathing fixed so Village and/or Village ID is no longer in the URL for a single request display

Single Request

---

client/src/components/DisplayComment/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/pages/Request.js

DisplayComment component created
Comment now displays for request 'Carpool Request - Tuesday' on single request page
Styling needed

Created DisplayComment component, got single comment to display

---

client/src/components/ReqsByVillager/index.js
client/src/pages/styles/profile.css

make the requests by villager displayed on profile page clickable 

---

client/src/components/CommentFormButton/index.js
client/src/components/DisplaySingleRequest/index.js

Added button to the single request page that we will later hook up to be able to add comments from the client-side.

Added a SUBMIT COMMENT button 

---

client/src/components/CommentForm/index.js
client/src/components/DisplayComment/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/components/FunkButton/index.js
client/src/pages/Request.js
client/src/utils/mutations.js

Annie got the comments to delete but we couldn't get them to refresh. Most recent updates allow for deleting and refreshing on client side. See commits.

Delete comments updates

---

client/src/components/ClaimRequestButton/index.js
client/src/components/CommentForm/index.js
client/src/components/DisplayComment/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/components/FunkButton/index.js

Cleaned up console logs
Moved addcomment mutation to the comment form component
Got comment form to clear of input value after mutations runs when form is submitted for adding a comment.

Comment Form

---

client/src/components/DisplayComment/index.js

Conditional rendering of the delete icon for comments is functional.

Comment Delete Conditional Rendering

---

client/src/components/CommentForm/index.js
client/src/components/CreateRequest/index.js
client/src/components/DisplayComment/index.js
client/src/components/DisplaySingleRequest/index.js

Comment array state moved to parent component DisplaySingleRequest.
Callback function for deleteComment change created on DisplaySingleRequest and sent as prop to DisplayComment to handle the mutation of deletion.
SetCommentList method sent to CommentForm component to run comment mutation and update the CommentList state so that it only re-renders DisplayComment.

RefetchQuery Replacement for CommentForm

---

server/schemas/resolvers.js

Cascading of comment deletion now deletes from the Request comments array

Cascading of comment deletion

---

client/src/pages/Village.js
client/src/utils/RequestContext.js
server/schemas/resolvers.js

Added RequestContext.js for future placement of global state for request
Cascading Delete Request (Tested in backend only):
- Deletes request from villager and village arrays
- Deletes all associated comments with request
- Deletes that single request
Needs:
- Test in frontend for delete request
- Resolution of rendering for delete request

Added RequestContext.js and Cascading Delete Request

---

client/src/components/DisplaySingleRequest/index.js

Added navigate after delete request to act similar to back btn

Added Navigate after Delete Request

---

client/src/components/CommentBox/index.js
client/src/components/CommentForm/index.js
client/src/components/DisplaySingleRequest/index.js
client/src/pages/Request.js

Added CommentBox component and moved all comment related components to it for separation of concern
- Moved CommentForm and DisplayComments to render in CommentBox
- Render CommentBox in parent Request page to separate the display of request and comments into two

Added CommentBox Component

---

client/src/components/EditReqForm.js/index.js
client/src/pages/About.js
client/src/pages/CreateReq.js
client/src/pages/CreateVillage.js
client/src/pages/EditProfile.js
client/src/pages/EditReq.js
client/src/pages/EditVillage.js
client/src/pages/Home.js
client/src/pages/Profile.js
client/src/pages/Request.js
client/src/pages/Search.js
client/src/pages/Village.js
client/src/pages/WhatVillage.js

- Commented out conditional Nav Bar from individual pages in the app (logic already housed in the App.js file)
- Deleted conditional Nav Bar logic from unused pages
- Added notes to EditReqForm's index.js file explaining why we should set min/max rows for MUI TextField component locally.

Removing NavBar logic from individual pages
